services:
  db:
    image: postgres:16.4
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - db:/var/lib/postgresql/data
      - ./.docker/db:/docker-entrypoint-initdb.d/

  app:
    build: .
    volumes:
      - .:/home/node/app
    ports:
      - ${PORT:-3000}:3000
    depends_on:
      db:
        condition: service_healthy
        restart: true

volumes:
  db:
    driver: local
